# Generated by Django 5.1.6 on 2026-04-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0004_predictionlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Raw text sent for prediction')),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(choices=[('xgboost', 'XGBoost'), ('distilbert', 'DistilBERT')], default='xgboost', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Prediction Log',
                'verbose_name_plural': 'Public Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicFeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_label', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='model_app.publicpredictionlog')),
            ],
            options={
                'verbose_name': 'Public Feedback Entry',
                'verbose_name_plural': 'Public Feedback Entries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
